language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - composer self-update
    - composer require --dev --no-update symfony/symfony:^2.8||^3.0

install:
    - composer install
